spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rideDB
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: RideService
server:
  port: 4568

driver-service:
  name: driver-service
  url: http://localhost:4567/drivers

